import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import vuetify from 'vite-plugin-vuetify';
import { fileURLToPath, URL } from 'node:url';
import viteCompression from 'vite-plugin-compression';
import { seoInjectPlugin } from './src/lib/plugins/seo-inject.js';
import { prerenderPlugin } from './src/lib/plugins/prerender.js';
import { seoStaticPlugin } from './src/lib/plugins/seo-static.js';
import { assertConfigLoaded, CONFIG_PLACEHOLDER } from './src/lib/helpers/configGuard.js';

// Load config - will be generated by generateConfig.js script
let appConfig = CONFIG_PLACEHOLDER;
try {
  const configModule = await import('./src/config/index.js');
  appConfig = configModule.default;
} catch {
  console.warn('Could not load config, using defaults. Run npm run config first.');
}

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  assertConfigLoaded(appConfig, mode);
  return {
    plugins: [
      seoInjectPlugin(appConfig),
      prerenderPlugin(appConfig, mode),
      seoStaticPlugin(appConfig),
      vue({
        template: {
          compilerOptions: {
            // Support for runtime template compilation
            isCustomElement: (tag) => tag.startsWith('ion-'),
          },
        },
      }),
      // https://github.com/vuetifyjs/vuetify-loader/tree/master/packages/vite-plugin
      vuetify({
        autoImport: true,
      }),
      // Brotli compression for production
      viteCompression({
        verbose: true,
        disable: mode !== 'production',
        threshold: 10240,
        algorithm: 'brotliCompress',
        ext: '.br',
        deleteOriginFile: false,
      }),
      // Gzip compression fallback for production
      viteCompression({
        verbose: true,
        disable: mode !== 'production',
        threshold: 10240,
        algorithm: 'gzip',
        ext: '.gz',
        deleteOriginFile: false,
      }),
    ],

    define: {
      __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: 'false',
    },

    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url)),
      },
      extensions: ['.js', '.json', '.jsx', '.mjs', '.ts', '.tsx', '.vue'],
    },

    server: {
      port: appConfig.port || 8080,
      strictPort: false,
      // Uncomment to proxy API requests
      // proxy: {
      //   '/api': {
      //     target: 'http://localhost:3000',
      //     changeOrigin: true,
      //   },
      // },
    },

    preview: {
      port: appConfig.port || 8080,
    },

    build: {
      outDir: 'dist',
      assetsDir: 'assets',
      sourcemap: mode !== 'production',
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes('node_modules')) {
              if (['vue', 'vue-router', 'pinia'].some((pkg) => id.includes(`/${pkg}/`))) return 'vue-vendor';
              if (id.includes('/vuetify/')) return 'vuetify-vendor';
              if (['axios', 'lodash-es', 'dayjs'].some((pkg) => id.includes(`/${pkg}/`))) return 'utils-vendor';
            }
          },
        },
      },
      // Increase chunk size warning limit
      chunkSizeWarningLimit: 1000,
    },

    optimizeDeps: {
      include: ['vue', 'vue-router', 'pinia', 'vuetify', 'axios', 'lodash-es', 'dayjs', 'marked', 'aos'],
    },
  };
});
