apiVersion: apps/v1
kind: Deployment
metadata:
  name: pierreb-vue
  namespace: pierreb-projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pierreb-vue
  template:
    metadata:
      labels:
        app: pierreb-vue
    spec:
      containers:
        - name: app
          image: ghcr.io/pierreb-projects/pierreb_vue:master@sha256:0f4baf19b645790f895c5f1358772182848e3ad574640d80e12491e935adcacd # {"$imagepolicy": "flux-system:pierreb-vue"}
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: 'pierreb'
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: pierreb-vue
  namespace: pierreb-projects
spec:
  selector:
    app: pierreb-vue
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pierreb-me
  namespace: pierreb-projects
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts: [pierreb.me]
      secretName: pierreb-me-tls
  rules:
    - host: pierreb.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pierreb-vue
                port:
                  number: 80
