#!/bin/sh
# guard-commit-cross-org-refs — block cross-org closing references in commits.
#
# This is a PUBLIC repository whose CHANGELOG is generated by semantic-release
# from commit footers. A GitHub closing keyword (Closes/Fixes/Resolves) that
# targets ANOTHER org's issue (`<owner>/<repo>#N` where `<owner>` is not this
# repo's org) ends up rendered as a public→private dead link in the changelog —
# a tracker leak. Reference a private/cross-org tracker with a body-only
# `tracks: <owner>/<repo>#N` line instead, and use `Closes #N` only for issues
# in THIS repo.
#
# Allowed:   Closes #123 · closes pierreb-devkit/Vue#123 · tracks: other-org/repo#7
# Blocked:   Closes other-org/repo#7 · Fixes another-org/project#28
#
# Wired from .husky/commit-msg (runs before commitlint). Exit 1 blocks the commit.

OWN_ORG="pierreb-devkit"
MSG_FILE="$1"
[ -f "$MSG_FILE" ] || exit 0

# Closing keyword + owner/repo#N, owner captured. Case-insensitive.
BAD=$(grep -Eio '(close[sd]?|fix(es|ed)?|resolve[sd]?)[[:space:]]+[A-Za-z0-9._-]+/[A-Za-z0-9._-]+#[0-9]+' "$MSG_FILE" 2>/dev/null \
  | grep -Eiv "[[:space:]]${OWN_ORG}/")

if [ -n "$BAD" ]; then
  echo "✖ commit blocked — cross-org closing reference in a PUBLIC repo:" >&2
  printf '%s\n' "$BAD" | sed 's/^/    /' >&2
  echo "" >&2
  echo "  A closing keyword (closes/fixes/resolves) pointing at another org leaks a" >&2
  echo "  private tracker into the generated CHANGELOG. Use a body-only" >&2
  echo "  'tracks: <owner>/<repo>#N' reference instead; keep 'Closes #N' for this repo." >&2
  exit 1
fi
exit 0
