name: Build & Push (master)

on:
  push:
    branches: ['master']

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/pierreb-projects/pierreb_vue
          tags: |
            type=raw,value=master
            type=sha,prefix=sha-

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_ENV=pierreb
            DEVKIT_VUE_app_title=PierreBrisorgueil
            DEVKIT_VUE_api_host=api.pierreb.me
            DEVKIT_VUE_api_protocol=https
            DEVKIT_VUE_api_port=
            DEVKIT_VUE_cookie_prefix=pierreb
